### ISSUE TITLE
I amazing post about Faster RCNN. it's help me a lot. When you write next post ?

### ISSUE THREAD

**Issue by ThorPham** [dongjk/faster_rcnn_keras#1]

**Comment by dongjk** [comment]
I'm glad you like it, you will see it soon as I already started writing and implementation.

**Comment by ThorPham** [comment]
Thank you so much!!

**Comment by ThorPham** [comment]
Can you explain Fully convolution network in RPN in faster RCNN . I don't undertand why anchor box different size can put in CNN to same size output

**Comment by dongjk** [comment]
Anchors will not used in input, it will be used as an assistent to help produce output. in post each input is a 3x3 feature map tile, will generate 9 anchors to help produce 1x9 and 4x9 outputs.
we can see input / ouput are all fixed size, we deal the non-fix size part in preprocessing phase: slice not fixed size feature map to 3x3 tiles.

**Comment by ThorPham** [comment]
In RPN how to classifier object orr non object. It's different size. Can you explain ?

**Comment by dongjk** [comment]
do you mean fg(object) and bg(non object) have different numbers?  e.g. if we have 100x9 anchors, there may have only 50 of them are fg, left 850 are bg?

**Comment by ThorPham** [comment]
I don't know how to classifier object or non-object when anchor box different size. Because RPN not using ROI pooling to fix size feature

**Comment by dongjk** [comment]
RoI pooling will fix size feature because RCNN input are non-fix size RoIs, it need a pooling layer,

but for RPN, the inputs are neither RoIs nor anchors, the inputs are fix size feature tiles, here have shape (batch, 3,3,1532), this tile is all RPN need for input.
you must understand anchors are not participant RPN input, it just use to generate RPN output targets.

**Comment by ThorPham** [comment]
very very thank you. It's help me a lot. Thank you so much
